### ISSUE TITLE
SN Public and Service Provider Filters Change

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1412]
Goal: Facilitate the user's filter options from being hidden and having to click on the filter for filters to appear to have them upfront without question of where filters could be found 
- Keep grid view as it's the only state 
- Move all functionality from the below screenshot and have the straight layout as the screenshot 2

<img width="274" alt="Screenshot 2020-11-19 132752" src="https://user-images.githubusercontent.com/65787629/99726195-0f360d80-2a6b-11eb-8cdc-a2e41fe6387f.png">

Desktop View 
---------------
<img width="798" alt="Screenshot 2020-11-19 135129" src="https://user-images.githubusercontent.com/65787629/99728490-5a9deb00-2a6e-11eb-9b94-aaac7dfc8ecf.png">

<img width="805" alt="Screenshot 2020-11-19 140708" src="https://user-images.githubusercontent.com/65787629/99729957-8a4df280-2a70-11eb-9461-8b6eb3339362.png">

Mobile View For Service Provider and Public View
------------------
<img width="362" alt="Screenshot 2020-11-19 140328" src="https://user-images.githubusercontent.com/65787629/99729642-127fc800-2a70-11eb-9ad2-6b93c2cedd08.png">

Map Click on change fro desktop on #1399 
- Beneficiary Check-In and Refer Elsewhere buttons on #1413

**Comment by EnriqueCorado** [comment]
- add the map icon next to the search bar as displayed below

<img width="338" alt="Screenshot 2020-11-30 144501" src="https://user-images.githubusercontent.com/65787629/100674816-a7a97900-331a-11eb-8e29-00cb20505bcd.png">

**Comment by jkondrat** [comment]
@EnriqueCorado should we remove the free text search and replace it with service type dropdown?

**Comment by EnriqueCorado** [comment]
@jkondrat no, keep it as the filter from the current filter. Where users can type in and the dropdown will update
- otherwise, users will have to keep scrolling through the dropdown to find the service 

<img width="272" alt="Screenshot 2020-12-04 071625" src="https://user-images.githubusercontent.com/65787629/101180605-a5883880-3600-11eb-9a67-7b13090336ca.png">


<img width="276" alt="Screenshot 2020-12-04 071715" src="https://user-images.githubusercontent.com/65787629/101180696-c05aad00-3600-11eb-87d6-d9867b73b14f.png">

**Comment by jkondrat** [comment]
@EnriqueCorado I see. The users are also allowed to search in organization names, should we keep that input?

**Comment by EnriqueCorado** [comment]
@jkondrat yes! Thank you

**Comment by abaranowska1** [comment]
@jkondrat I found a few things that need to be fixed:
1. As @EnriqueCorado said the Zip Code string name takes two lines for example on mobile #1534 
2. Also on mobile there is a few UI issues, for example 
- The titles of the search, service type, and location don't start from the one place, the search title is moved to the right
- The buttons should be centered, I checked it also on iOS
- This Zip Code string name takes two lines
![image](https://user-images.githubusercontent.com/61964176/103883766-e8e13580-50dd-11eb-9bef-9df589c1b4ce.png)
![image](https://user-images.githubusercontent.com/61964176/103883774-ee3e8000-50dd-11eb-8aba-8ad401155b05.png)
3. On mobile there is an issue with displaying the old filter modal after I use the new filters and click the Apply button the modal is displayed. 
![image](https://user-images.githubusercontent.com/61964176/103883925-247bff80-50de-11eb-8da6-ede567b62c6a.png)
![Peek 2021-01-07 11-33](https://user-images.githubusercontent.com/61964176/103883937-280f8680-50de-11eb-96cb-a8501a119e32.gif)
4. Clear button doesn't clear Service Types and Locations 
![Peek 2021-01-07 11-28](https://user-images.githubusercontent.com/61964176/103884035-4c6b6300-50de-11eb-9b41-113171235f57.gif)
5. The Service Type dropdown is higher than the rest fields ( City, County, ZipCode)
![image](https://user-images.githubusercontent.com/61964176/103884116-686f0480-50de-11eb-9c69-857fec78cd5c.png)
6. If there are more than 3/4 taxonomies, the Location dropdowns are unreadable, they are too narrow or the whole field is moved to the next line. On mobile, it looks as before. 
![image](https://user-images.githubusercontent.com/61964176/103884208-86d50000-50de-11eb-894d-9fc11e24cf87.png)
![image](https://user-images.githubusercontent.com/61964176/103884217-8a688700-50de-11eb-9da0-567fc7b7b5f4.png)
![image](https://user-images.githubusercontent.com/61964176/103884616-21cdda00-50df-11eb-85d3-6a951f601044.png)
7. The filter/search section is too big for mobile and the map is unreadable
![image](https://user-images.githubusercontent.com/61964176/103885157-dff16380-50df-11eb-999b-65c5fd731492.png)
8. Also on map view this section doesn't look good for me 
![image](https://user-images.githubusercontent.com/61964176/103885246-ff888c00-50df-11eb-84d7-ac0605ae4bea.png)
9. Public view on mobile - this section is too big, it takes half of the page and also it contains UI issues from point 2
![image](https://user-images.githubusercontent.com/61964176/103885428-4bd3cc00-50e0-11eb-9aff-7e49c327c0ab.png)
![image](https://user-images.githubusercontent.com/61964176/103885441-51c9ad00-50e0-11eb-9f5d-7c3e7ff6a99c.png)
10. The buttons should be centered, because now they are aligned to the bottom
![image](https://user-images.githubusercontent.com/61964176/103885685-ab31dc00-50e0-11eb-9ee7-ceb58005a9c4.png)

**Comment by jkondrat** [comment]
@abaranowska1 I have fixed all the issues, but the filters on mobiles with small screens are still taking too much space - I'll wait for @EnriqueCorado 's call, but I think it would make sense to use a modal there

**Comment by EnriqueCorado** [comment]
@jkondrat having a modal does make more sense on the limited real state on mobile

**Comment by abaranowska1** [comment]
**Tested**
@jkondrat 
1. The search bar doesn't work on mobile 
![Peek 2021-01-11 10-15](https://user-images.githubusercontent.com/61964176/104164203-e04b7080-53f7-11eb-9908-c9730a6547b8.gif)

2. Please remove the unnecessary text above the search bar and center the buttons. 
NOW: 
![Selection_787](https://user-images.githubusercontent.com/61964176/104164239-ec373280-53f7-11eb-804b-d17f8e87f767.png)
![Selection_785](https://user-images.githubusercontent.com/61964176/104164245-ed685f80-53f7-11eb-94e6-3c2a6de461e4.png)
BEFORE:
![Selection_789](https://user-images.githubusercontent.com/61964176/104164353-14bf2c80-53f8-11eb-99c4-26f7c79cf56a.png)
![image](https://user-images.githubusercontent.com/61964176/104164496-4801bb80-53f8-11eb-903d-8b5ea51d8fbb.png)

3. I think we can come back to this modal ( it will resolve the UI issues that exist now and also the problem with the field ZIP Code witch takes two lines) 
NOW: 
![Selection_786](https://user-images.githubusercontent.com/61964176/104164877-dd04b480-53f8-11eb-89b7-6d052d5a49b0.png)

BEFORE:
![Selection_793](https://user-images.githubusercontent.com/61964176/104164891-e261ff00-53f8-11eb-8ce2-a2707ad1aad7.png)

**Comment by jkondrat** [comment]
@kdondziak it seems that the search bar was broken in #1529 : the exception is: 
```
Uncaught TypeError: _this.props.onSearch is not a function
  at SearchBar._this.search (search-bar.tsx:43)
```

**Comment by jkondrat** [comment]
@kdondziak It turned out to be a one liner, I will fix it as a part of this issue

**Comment by jkondrat** [comment]
@abaranowska1 I'm going to keep the current button layout as it's consistent with the desktop view

**Comment by abaranowska1** [comment]
**Tested with success**
- SN Public and SP Filter Changes were added to the desktop view and fixed on the mobile view,
- Grid view is the only state, the List view was removed,
- All filters are in the one line on the web view
- All UI issues were fixed and now the whole page looks good
- The last issues from mobile were fixed and the search bar is working now
- Apply and Clear buttons work as expected 
![Selection_841](https://user-images.githubusercontent.com/61964176/104297041-abf0b680-54c2-11eb-9ea0-388893373455.png)
![Selection_840](https://user-images.githubusercontent.com/61964176/104297043-ac894d00-54c2-11eb-9220-3745dcc1a2cb.png)
![Selection_839](https://user-images.githubusercontent.com/61964176/104297046-ad21e380-54c2-11eb-9296-0d9795561672.png)
![Selection_838](https://user-images.githubusercontent.com/61964176/104297051-adba7a00-54c2-11eb-86c5-0d9601fd3536.png)
![Selection_837](https://user-images.githubusercontent.com/61964176/104297054-ae531080-54c2-11eb-80d4-36129df71ba4.png)
![Selection_836](https://user-images.githubusercontent.com/61964176/104297055-aeeba700-54c2-11eb-94ba-9b80e15de7ef.png)
![Peek 2021-01-12 10-34](https://user-images.githubusercontent.com/61964176/104297061-b0b56a80-54c2-11eb-836f-9e616ef8b41b.gif)

**Verified on:**
- Ubuntu 20.04
- Google Chrome Browser Version 85.0.4183.83
- Mobile 360x640
- iPhone X, Safari Browser

**Comment by meenupant** [comment]
@jkondrat @abaranowska1 For the Location filter fields (City, County, Zip Code) can you please include the "X" on each field to clear the choices just like you do it for Org Name and Service Type. Currently, the user has to click the "Clear" button to reset the fields to blank. This clears up all the fields, if someone wants to clear just the location fields but keep the Org Name and Service Type choices then this "X" within the location fields will help them do so. Thanks

**Comment by meenupant** [comment]
@jkondrat @abaranowska1 I searched for "American" and on clicked "Apply", it displayed the "American Civil..." record, and when I clicked this record I can see the details of this Organization. And when I click "Back to All Records" button on top left, I see only this "American Civil..." card/record and not the other records. The search field where I had put "American" is also blank. The only way I can see all the records again is when I click "Clear" button. Can you please let the search field be filled with the term "American" again, so the user can cross that field to see the display of all records whenever they wish to. Thanks

**Comment by abaranowska1** [comment]
@meenupant Please create new tasks for these two cases that you mentioned above, thanks.

**Comment by meenupant** [comment]
@abaranowska1 Sure @EnriqueCorado please note. Thanks
